Use config object for credentials
turbot/steampipe-plugin-databricks pull request #10
Opened 2023-08-29 11:26 UTC by karanpopat

# Example query results
<details>
  <summary>Results</summary>
  
```
Add example SQL query results here (please include the input queries as well)
```
</details>

2023-08-30 19:04 UTC, cbruno10 requested changes
@karanpopat Please see questions, thanks!

2023-08-30 19:04 UTC, cbruno10 commented on databricks/service.go
>  	if err != nil {
@karanpopat If multiple args are set for different auth methods, e.g., `config.Profile` and `config.Token` are set, what does the SDK do? Does it error or resolve creds in a certain order (if so, what order)?

2023-08-30 19:04 UTC, cbruno10 commented on databricks/service.go
>  		if databricksConfig.AccountHost != nil {
Is the host required for some or all tables for account and/or workspace connections?

2023-08-30 19:04 UTC, cbruno10 commented on databricks/service.go
> +	if databricksConfig.AccountId != nil {
Is account ID required for all account/workspace connections? If so, are there any other required args/env vars?

2023-08-31 09:19 UTC, rinzool commented on databricks/service.go
> +	if databricksConfig.AccountId != nil {
I think it's required only for the `connectDatabricksAccount` but not for `connectWorkspaceAccount` 
https://pkg.go.dev/github.com/databricks/databricks-sdk-go#readme-databricks-native-authentication

2023-08-31 09:19 UTC, rinzool commented on databricks/service.go
>  	} else if os.Getenv("DATABRICKS_CONFIG_PROFILE") == "" {
If I understand this correctly, if we setup a `profile` in `databrickscfg` file, we will have a value in `config.Profile`
**But** line 32 check if environment variable `DATABRICKS_CONFIG_PROFILE` is set (which is not the case), so we will go in the condtiion (which is not what we want)
I think you should replace line 32 with
```go
} else if databricksConfig.ConfigFilePath == nil {
```

2023-08-31 12:36 UTC, karanpopat commented on databricks/service.go
>  	if err != nil {
It errors with `validate: more than one authorization method configured`
The order in which I am checking and setting credentials are
1. Profile
2. Token
3. Username/Password

2023-08-31 12:38 UTC, karanpopat commented on databricks/service.go
>  		if databricksConfig.AccountHost != nil {
Host is required for all the requests.
It is not `required` in the config settings because it can be set in the profile args

2023-08-31 12:40 UTC, karanpopat commented on databricks/service.go
> +	if databricksConfig.AccountId != nil {
AccountId is not always required. I am using the account id as a part of common columns which would be a good to have column while using aggregators.
There is no other API to fetch the account details of the current user. So we are using the account id from config.

2023-08-31 12:46 UTC, karanpopat commented on databricks/service.go
>  	} else if os.Getenv("DATABRICKS_CONFIG_PROFILE") == "" {
hey @rinzool 
The order in which we prioritize the credentials passed is 
1. Profile
2. Access token
3. Username/Password

So in line 32, I mean to check whether the `profile` is already set in the env vars. If it is not set, only then would I be checking for other config args to set in the Config object.

2024-01-05 04:55 UTC, madhushreeray30 approved these changes

2024-01-22 13:37 UTC, cbruno10 approved these changes

2024-01-23 05:32 UTC, merged